/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_hello__
  (JNIEnv *, jclass);

/*
 * Class:     JNI
 * Method:    hello
 * Signature: (Ljava/lang/String;D[I)I
 */
JNIEXPORT jint JNICALL Java_JNI_hello__Ljava_lang_String_2D_3I
  (JNIEnv *, jobject, jstring, jdouble, jintArray);

#ifdef __cplusplus
}
#endif
#endif
