/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    hello
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JNI_hello
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
